version: '3.4'
services:
  mssql:
    container_name: mssql-db
    hostname: mssql-db
    user: root
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Anhbeo123'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1455:1433"
    volumes:
      - ./data-volume/data:/var/opt/mssql/data
      - ./data-volume/log:/var/opt/mssql/log
      - ./data-volume/secrets:/var/opt/mssql/secrets